// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nl/tudelft/cs4160/trustchain_android/Message.proto

package nl.tudelft.cs4160.trustchain_android.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    boolean hasHalfBlock();
    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getHalfBlock();
    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder getHalfBlockOrBuilder();

    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    boolean hasCrawlRequest();
    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getCrawlRequest();
    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder getCrawlRequestOrBuilder();
  }
  /**
   * Protobuf type {@code message.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder subBuilder = null;
              if (halfBlock_ != null) {
                subBuilder = halfBlock_.toBuilder();
              }
              halfBlock_ = input.readMessage(nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(halfBlock_);
                halfBlock_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder subBuilder = null;
              if (crawlRequest_ != null) {
                subBuilder = crawlRequest_.toBuilder();
              }
              crawlRequest_ = input.readMessage(nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(crawlRequest_);
                crawlRequest_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.Builder.class);
    }

    public static final int HALFBLOCK_FIELD_NUMBER = 1;
    private nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock halfBlock_;
    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    public boolean hasHalfBlock() {
      return halfBlock_ != null;
    }
    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getHalfBlock() {
      return halfBlock_ == null ? nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.getDefaultInstance() : halfBlock_;
    }
    /**
     * <code>.message.TrustChainBlock halfBlock = 1;</code>
     */
    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder getHalfBlockOrBuilder() {
      return getHalfBlock();
    }

    public static final int CRAWLREQUEST_FIELD_NUMBER = 2;
    private nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest crawlRequest_;
    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    public boolean hasCrawlRequest() {
      return crawlRequest_ != null;
    }
    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getCrawlRequest() {
      return crawlRequest_ == null ? nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.getDefaultInstance() : crawlRequest_;
    }
    /**
     * <code>.message.CrawlRequest crawlRequest = 2;</code>
     */
    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder getCrawlRequestOrBuilder() {
      return getCrawlRequest();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (halfBlock_ != null) {
        output.writeMessage(1, getHalfBlock());
      }
      if (crawlRequest_ != null) {
        output.writeMessage(2, getCrawlRequest());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (halfBlock_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHalfBlock());
      }
      if (crawlRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCrawlRequest());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message)) {
        return super.equals(obj);
      }
      nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message other = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message) obj;

      boolean result = true;
      result = result && (hasHalfBlock() == other.hasHalfBlock());
      if (hasHalfBlock()) {
        result = result && getHalfBlock()
            .equals(other.getHalfBlock());
      }
      result = result && (hasCrawlRequest() == other.hasCrawlRequest());
      if (hasCrawlRequest()) {
        result = result && getCrawlRequest()
            .equals(other.getCrawlRequest());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHalfBlock()) {
        hash = (37 * hash) + HALFBLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getHalfBlock().hashCode();
      }
      if (hasCrawlRequest()) {
        hash = (37 * hash) + CRAWLREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getCrawlRequest().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Message)
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.Builder.class);
      }

      // Construct using nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (halfBlockBuilder_ == null) {
          halfBlock_ = null;
        } else {
          halfBlock_ = null;
          halfBlockBuilder_ = null;
        }
        if (crawlRequestBuilder_ == null) {
          crawlRequest_ = null;
        } else {
          crawlRequest_ = null;
          crawlRequestBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_Message_descriptor;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message getDefaultInstanceForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.getDefaultInstance();
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message build() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message buildPartial() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message result = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message(this);
        if (halfBlockBuilder_ == null) {
          result.halfBlock_ = halfBlock_;
        } else {
          result.halfBlock_ = halfBlockBuilder_.build();
        }
        if (crawlRequestBuilder_ == null) {
          result.crawlRequest_ = crawlRequest_;
        } else {
          result.crawlRequest_ = crawlRequestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message) {
          return mergeFrom((nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message other) {
        if (other == nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasHalfBlock()) {
          mergeHalfBlock(other.getHalfBlock());
        }
        if (other.hasCrawlRequest()) {
          mergeCrawlRequest(other.getCrawlRequest());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock halfBlock_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder> halfBlockBuilder_;
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public boolean hasHalfBlock() {
        return halfBlockBuilder_ != null || halfBlock_ != null;
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getHalfBlock() {
        if (halfBlockBuilder_ == null) {
          return halfBlock_ == null ? nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.getDefaultInstance() : halfBlock_;
        } else {
          return halfBlockBuilder_.getMessage();
        }
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public Builder setHalfBlock(nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock value) {
        if (halfBlockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          halfBlock_ = value;
          onChanged();
        } else {
          halfBlockBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public Builder setHalfBlock(
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder builderForValue) {
        if (halfBlockBuilder_ == null) {
          halfBlock_ = builderForValue.build();
          onChanged();
        } else {
          halfBlockBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public Builder mergeHalfBlock(nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock value) {
        if (halfBlockBuilder_ == null) {
          if (halfBlock_ != null) {
            halfBlock_ =
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.newBuilder(halfBlock_).mergeFrom(value).buildPartial();
          } else {
            halfBlock_ = value;
          }
          onChanged();
        } else {
          halfBlockBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public Builder clearHalfBlock() {
        if (halfBlockBuilder_ == null) {
          halfBlock_ = null;
          onChanged();
        } else {
          halfBlock_ = null;
          halfBlockBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder getHalfBlockBuilder() {
        
        onChanged();
        return getHalfBlockFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder getHalfBlockOrBuilder() {
        if (halfBlockBuilder_ != null) {
          return halfBlockBuilder_.getMessageOrBuilder();
        } else {
          return halfBlock_ == null ?
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.getDefaultInstance() : halfBlock_;
        }
      }
      /**
       * <code>.message.TrustChainBlock halfBlock = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder> 
          getHalfBlockFieldBuilder() {
        if (halfBlockBuilder_ == null) {
          halfBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder>(
                  getHalfBlock(),
                  getParentForChildren(),
                  isClean());
          halfBlock_ = null;
        }
        return halfBlockBuilder_;
      }

      private nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest crawlRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder> crawlRequestBuilder_;
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public boolean hasCrawlRequest() {
        return crawlRequestBuilder_ != null || crawlRequest_ != null;
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getCrawlRequest() {
        if (crawlRequestBuilder_ == null) {
          return crawlRequest_ == null ? nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.getDefaultInstance() : crawlRequest_;
        } else {
          return crawlRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public Builder setCrawlRequest(nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest value) {
        if (crawlRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          crawlRequest_ = value;
          onChanged();
        } else {
          crawlRequestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public Builder setCrawlRequest(
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder builderForValue) {
        if (crawlRequestBuilder_ == null) {
          crawlRequest_ = builderForValue.build();
          onChanged();
        } else {
          crawlRequestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public Builder mergeCrawlRequest(nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest value) {
        if (crawlRequestBuilder_ == null) {
          if (crawlRequest_ != null) {
            crawlRequest_ =
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.newBuilder(crawlRequest_).mergeFrom(value).buildPartial();
          } else {
            crawlRequest_ = value;
          }
          onChanged();
        } else {
          crawlRequestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public Builder clearCrawlRequest() {
        if (crawlRequestBuilder_ == null) {
          crawlRequest_ = null;
          onChanged();
        } else {
          crawlRequest_ = null;
          crawlRequestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder getCrawlRequestBuilder() {
        
        onChanged();
        return getCrawlRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder getCrawlRequestOrBuilder() {
        if (crawlRequestBuilder_ != null) {
          return crawlRequestBuilder_.getMessageOrBuilder();
        } else {
          return crawlRequest_ == null ?
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.getDefaultInstance() : crawlRequest_;
        }
      }
      /**
       * <code>.message.CrawlRequest crawlRequest = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder> 
          getCrawlRequestFieldBuilder() {
        if (crawlRequestBuilder_ == null) {
          crawlRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder>(
                  getCrawlRequest(),
                  getParentForChildren(),
                  isClean());
          crawlRequest_ = null;
        }
        return crawlRequestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Message)
    }

    // @@protoc_insertion_point(class_scope:message.Message)
    private static final nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message();
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrustChainBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.TrustChainBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes public_key = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>int32 sequence_number = 2;</code>
     */
    int getSequenceNumber();

    /**
     * <code>bytes link_public_key = 3;</code>
     */
    com.google.protobuf.ByteString getLinkPublicKey();

    /**
     * <code>int32 link_sequence_number = 4;</code>
     */
    int getLinkSequenceNumber();

    /**
     * <code>bytes previous_hash = 5;</code>
     */
    com.google.protobuf.ByteString getPreviousHash();

    /**
     * <code>bytes signature = 6;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>bytes transaction = 7;</code>
     */
    com.google.protobuf.ByteString getTransaction();
  }
  /**
   * Protobuf type {@code message.TrustChainBlock}
   */
  public  static final class TrustChainBlock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.TrustChainBlock)
      TrustChainBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrustChainBlock.newBuilder() to construct.
    private TrustChainBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrustChainBlock() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      sequenceNumber_ = 0;
      linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      linkSequenceNumber_ = 0;
      previousHash_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      transaction_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrustChainBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              publicKey_ = input.readBytes();
              break;
            }
            case 16: {

              sequenceNumber_ = input.readInt32();
              break;
            }
            case 26: {

              linkPublicKey_ = input.readBytes();
              break;
            }
            case 32: {

              linkSequenceNumber_ = input.readInt32();
              break;
            }
            case 42: {

              previousHash_ = input.readBytes();
              break;
            }
            case 50: {

              signature_ = input.readBytes();
              break;
            }
            case 58: {

              transaction_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_TrustChainBlock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_TrustChainBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder.class);
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 2;
    private int sequenceNumber_;
    /**
     * <code>int32 sequence_number = 2;</code>
     */
    public int getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int LINK_PUBLIC_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString linkPublicKey_;
    /**
     * <code>bytes link_public_key = 3;</code>
     */
    public com.google.protobuf.ByteString getLinkPublicKey() {
      return linkPublicKey_;
    }

    public static final int LINK_SEQUENCE_NUMBER_FIELD_NUMBER = 4;
    private int linkSequenceNumber_;
    /**
     * <code>int32 link_sequence_number = 4;</code>
     */
    public int getLinkSequenceNumber() {
      return linkSequenceNumber_;
    }

    public static final int PREVIOUS_HASH_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString previousHash_;
    /**
     * <code>bytes previous_hash = 5;</code>
     */
    public com.google.protobuf.ByteString getPreviousHash() {
      return previousHash_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 6;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int TRANSACTION_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString transaction_;
    /**
     * <code>bytes transaction = 7;</code>
     */
    public com.google.protobuf.ByteString getTransaction() {
      return transaction_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!publicKey_.isEmpty()) {
        output.writeBytes(1, publicKey_);
      }
      if (sequenceNumber_ != 0) {
        output.writeInt32(2, sequenceNumber_);
      }
      if (!linkPublicKey_.isEmpty()) {
        output.writeBytes(3, linkPublicKey_);
      }
      if (linkSequenceNumber_ != 0) {
        output.writeInt32(4, linkSequenceNumber_);
      }
      if (!previousHash_.isEmpty()) {
        output.writeBytes(5, previousHash_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(6, signature_);
      }
      if (!transaction_.isEmpty()) {
        output.writeBytes(7, transaction_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (sequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sequenceNumber_);
      }
      if (!linkPublicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, linkPublicKey_);
      }
      if (linkSequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, linkSequenceNumber_);
      }
      if (!previousHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, previousHash_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, signature_);
      }
      if (!transaction_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, transaction_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock)) {
        return super.equals(obj);
      }
      nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock other = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock) obj;

      boolean result = true;
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && (getSequenceNumber()
          == other.getSequenceNumber());
      result = result && getLinkPublicKey()
          .equals(other.getLinkPublicKey());
      result = result && (getLinkSequenceNumber()
          == other.getLinkSequenceNumber());
      result = result && getPreviousHash()
          .equals(other.getPreviousHash());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && getTransaction()
          .equals(other.getTransaction());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceNumber();
      hash = (37 * hash) + LINK_PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getLinkPublicKey().hashCode();
      hash = (37 * hash) + LINK_SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getLinkSequenceNumber();
      hash = (37 * hash) + PREVIOUS_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousHash().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransaction().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.TrustChainBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.TrustChainBlock)
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_TrustChainBlock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_TrustChainBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.Builder.class);
      }

      // Construct using nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        sequenceNumber_ = 0;

        linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;

        linkSequenceNumber_ = 0;

        previousHash_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        transaction_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_TrustChainBlock_descriptor;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getDefaultInstanceForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.getDefaultInstance();
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock build() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock buildPartial() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock result = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock(this);
        result.publicKey_ = publicKey_;
        result.sequenceNumber_ = sequenceNumber_;
        result.linkPublicKey_ = linkPublicKey_;
        result.linkSequenceNumber_ = linkSequenceNumber_;
        result.previousHash_ = previousHash_;
        result.signature_ = signature_;
        result.transaction_ = transaction_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock) {
          return mergeFrom((nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock other) {
        if (other == nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock.getDefaultInstance()) return this;
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getSequenceNumber() != 0) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.getLinkPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setLinkPublicKey(other.getLinkPublicKey());
        }
        if (other.getLinkSequenceNumber() != 0) {
          setLinkSequenceNumber(other.getLinkSequenceNumber());
        }
        if (other.getPreviousHash() != com.google.protobuf.ByteString.EMPTY) {
          setPreviousHash(other.getPreviousHash());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.getTransaction() != com.google.protobuf.ByteString.EMPTY) {
          setTransaction(other.getTransaction());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 1;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private int sequenceNumber_ ;
      /**
       * <code>int32 sequence_number = 2;</code>
       */
      public int getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>int32 sequence_number = 2;</code>
       */
      public Builder setSequenceNumber(int value) {
        
        sequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sequence_number = 2;</code>
       */
      public Builder clearSequenceNumber() {
        
        sequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes link_public_key = 3;</code>
       */
      public com.google.protobuf.ByteString getLinkPublicKey() {
        return linkPublicKey_;
      }
      /**
       * <code>bytes link_public_key = 3;</code>
       */
      public Builder setLinkPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes link_public_key = 3;</code>
       */
      public Builder clearLinkPublicKey() {
        
        linkPublicKey_ = getDefaultInstance().getLinkPublicKey();
        onChanged();
        return this;
      }

      private int linkSequenceNumber_ ;
      /**
       * <code>int32 link_sequence_number = 4;</code>
       */
      public int getLinkSequenceNumber() {
        return linkSequenceNumber_;
      }
      /**
       * <code>int32 link_sequence_number = 4;</code>
       */
      public Builder setLinkSequenceNumber(int value) {
        
        linkSequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 link_sequence_number = 4;</code>
       */
      public Builder clearLinkSequenceNumber() {
        
        linkSequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString previousHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes previous_hash = 5;</code>
       */
      public com.google.protobuf.ByteString getPreviousHash() {
        return previousHash_;
      }
      /**
       * <code>bytes previous_hash = 5;</code>
       */
      public Builder setPreviousHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        previousHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes previous_hash = 5;</code>
       */
      public Builder clearPreviousHash() {
        
        previousHash_ = getDefaultInstance().getPreviousHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 6;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes transaction = 7;</code>
       */
      public com.google.protobuf.ByteString getTransaction() {
        return transaction_;
      }
      /**
       * <code>bytes transaction = 7;</code>
       */
      public Builder setTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes transaction = 7;</code>
       */
      public Builder clearTransaction() {
        
        transaction_ = getDefaultInstance().getTransaction();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.TrustChainBlock)
    }

    // @@protoc_insertion_point(class_scope:message.TrustChainBlock)
    private static final nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock();
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrustChainBlock>
        PARSER = new com.google.protobuf.AbstractParser<TrustChainBlock>() {
      public TrustChainBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TrustChainBlock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrustChainBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrustChainBlock> getParserForType() {
      return PARSER;
    }

    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.TrustChainBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CrawlRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.CrawlRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes public_key = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>int32 requested_sequence_number = 2;</code>
     */
    int getRequestedSequenceNumber();

    /**
     * <code>int32 limit = 3;</code>
     */
    int getLimit();
  }
  /**
   * Protobuf type {@code message.CrawlRequest}
   */
  public  static final class CrawlRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.CrawlRequest)
      CrawlRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CrawlRequest.newBuilder() to construct.
    private CrawlRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CrawlRequest() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      requestedSequenceNumber_ = 0;
      limit_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CrawlRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              publicKey_ = input.readBytes();
              break;
            }
            case 16: {

              requestedSequenceNumber_ = input.readInt32();
              break;
            }
            case 24: {

              limit_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_CrawlRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_CrawlRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder.class);
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int REQUESTED_SEQUENCE_NUMBER_FIELD_NUMBER = 2;
    private int requestedSequenceNumber_;
    /**
     * <code>int32 requested_sequence_number = 2;</code>
     */
    public int getRequestedSequenceNumber() {
      return requestedSequenceNumber_;
    }

    public static final int LIMIT_FIELD_NUMBER = 3;
    private int limit_;
    /**
     * <code>int32 limit = 3;</code>
     */
    public int getLimit() {
      return limit_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!publicKey_.isEmpty()) {
        output.writeBytes(1, publicKey_);
      }
      if (requestedSequenceNumber_ != 0) {
        output.writeInt32(2, requestedSequenceNumber_);
      }
      if (limit_ != 0) {
        output.writeInt32(3, limit_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (requestedSequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestedSequenceNumber_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, limit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest)) {
        return super.equals(obj);
      }
      nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest other = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest) obj;

      boolean result = true;
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && (getRequestedSequenceNumber()
          == other.getRequestedSequenceNumber());
      result = result && (getLimit()
          == other.getLimit());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + REQUESTED_SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedSequenceNumber();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.CrawlRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.CrawlRequest)
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_CrawlRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_CrawlRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.class, nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.Builder.class);
      }

      // Construct using nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        requestedSequenceNumber_ = 0;

        limit_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.internal_static_message_CrawlRequest_descriptor;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getDefaultInstanceForType() {
        return nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.getDefaultInstance();
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest build() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest buildPartial() {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest result = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest(this);
        result.publicKey_ = publicKey_;
        result.requestedSequenceNumber_ = requestedSequenceNumber_;
        result.limit_ = limit_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest) {
          return mergeFrom((nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest other) {
        if (other == nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest.getDefaultInstance()) return this;
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getRequestedSequenceNumber() != 0) {
          setRequestedSequenceNumber(other.getRequestedSequenceNumber());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 1;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private int requestedSequenceNumber_ ;
      /**
       * <code>int32 requested_sequence_number = 2;</code>
       */
      public int getRequestedSequenceNumber() {
        return requestedSequenceNumber_;
      }
      /**
       * <code>int32 requested_sequence_number = 2;</code>
       */
      public Builder setRequestedSequenceNumber(int value) {
        
        requestedSequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requested_sequence_number = 2;</code>
       */
      public Builder clearRequestedSequenceNumber() {
        
        requestedSequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <code>int32 limit = 3;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <code>int32 limit = 3;</code>
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 limit = 3;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.CrawlRequest)
    }

    // @@protoc_insertion_point(class_scope:message.CrawlRequest)
    private static final nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest();
    }

    public static nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CrawlRequest>
        PARSER = new com.google.protobuf.AbstractParser<CrawlRequest>() {
      public CrawlRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CrawlRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CrawlRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CrawlRequest> getParserForType() {
      return PARSER;
    }

    public nl.tudelft.cs4160.trustchain_android.message.MessageProto.CrawlRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_TrustChainBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_TrustChainBlock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CrawlRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CrawlRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2nl/tudelft/cs4160/trustchain_android/M" +
      "essage.proto\022\007message\"c\n\007Message\022+\n\thalf" +
      "Block\030\001 \001(\0132\030.message.TrustChainBlock\022+\n" +
      "\014crawlRequest\030\002 \001(\0132\025.message.CrawlReque" +
      "st\"\264\001\n\017TrustChainBlock\022\022\n\npublic_key\030\001 \001" +
      "(\014\022\027\n\017sequence_number\030\002 \001(\005\022\027\n\017link_publ" +
      "ic_key\030\003 \001(\014\022\034\n\024link_sequence_number\030\004 \001" +
      "(\005\022\025\n\rprevious_hash\030\005 \001(\014\022\021\n\tsignature\030\006" +
      " \001(\014\022\023\n\013transaction\030\007 \001(\014\"T\n\014CrawlReques" +
      "t\022\022\n\npublic_key\030\001 \001(\014\022!\n\031requested_seque",
      "nce_number\030\002 \001(\005\022\r\n\005limit\030\003 \001(\005B<\n,nl.tu" +
      "delft.cs4160.trustchain_android.messageB" +
      "\014MessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Message_descriptor,
        new java.lang.String[] { "HalfBlock", "CrawlRequest", });
    internal_static_message_TrustChainBlock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_TrustChainBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_TrustChainBlock_descriptor,
        new java.lang.String[] { "PublicKey", "SequenceNumber", "LinkPublicKey", "LinkSequenceNumber", "PreviousHash", "Signature", "Transaction", });
    internal_static_message_CrawlRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_CrawlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CrawlRequest_descriptor,
        new java.lang.String[] { "PublicKey", "RequestedSequenceNumber", "Limit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
