// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nl/tudelft/cs4160/trustchain_android/TempBlock.proto

package nl.tudelft.cs4160.trustchain_android.message;

public final class TempBlockProto {
  private TempBlockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string publickey = 1;</code>
     */
    boolean hasPublickey();
    /**
     * <code>required string publickey = 1;</code>
     */
    java.lang.String getPublickey();
    /**
     * <code>required string publickey = 1;</code>
     */
    com.google.protobuf.ByteString
        getPublickeyBytes();

    /**
     * <code>required int32 seqnumber = 2;</code>
     */
    boolean hasSeqnumber();
    /**
     * <code>required int32 seqnumber = 2;</code>
     */
    int getSeqnumber();

    /**
     * <code>required string linkpublickey = 3;</code>
     */
    boolean hasLinkpublickey();
    /**
     * <code>required string linkpublickey = 3;</code>
     */
    java.lang.String getLinkpublickey();
    /**
     * <code>required string linkpublickey = 3;</code>
     */
    com.google.protobuf.ByteString
        getLinkpublickeyBytes();

    /**
     * <code>required int32 linkseqnumber = 4;</code>
     */
    boolean hasLinkseqnumber();
    /**
     * <code>required int32 linkseqnumber = 4;</code>
     */
    int getLinkseqnumber();

    /**
     * <code>required string prevhash = 5;</code>
     */
    boolean hasPrevhash();
    /**
     * <code>required string prevhash = 5;</code>
     */
    java.lang.String getPrevhash();
    /**
     * <code>required string prevhash = 5;</code>
     */
    com.google.protobuf.ByteString
        getPrevhashBytes();

    /**
     * <code>required string signature = 6;</code>
     */
    boolean hasSignature();
    /**
     * <code>required string signature = 6;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>required string signature = 6;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>optional string message = 7;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 7;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 7;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code message.Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      publickey_ = "";
      seqnumber_ = 0;
      linkpublickey_ = "";
      linkseqnumber_ = 0;
      prevhash_ = "";
      signature_ = "";
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              publickey_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              seqnumber_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              linkpublickey_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              linkseqnumber_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              prevhash_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              signature_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.internal_static_message_Block_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.internal_static_message_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.class, nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.Builder.class);
    }

    private int bitField0_;
    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object publickey_;
    /**
     * <code>required string publickey = 1;</code>
     */
    public boolean hasPublickey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string publickey = 1;</code>
     */
    public java.lang.String getPublickey() {
      java.lang.Object ref = publickey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          publickey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string publickey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPublickeyBytes() {
      java.lang.Object ref = publickey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publickey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQNUMBER_FIELD_NUMBER = 2;
    private int seqnumber_;
    /**
     * <code>required int32 seqnumber = 2;</code>
     */
    public boolean hasSeqnumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 seqnumber = 2;</code>
     */
    public int getSeqnumber() {
      return seqnumber_;
    }

    public static final int LINKPUBLICKEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object linkpublickey_;
    /**
     * <code>required string linkpublickey = 3;</code>
     */
    public boolean hasLinkpublickey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string linkpublickey = 3;</code>
     */
    public java.lang.String getLinkpublickey() {
      java.lang.Object ref = linkpublickey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          linkpublickey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string linkpublickey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLinkpublickeyBytes() {
      java.lang.Object ref = linkpublickey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkpublickey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINKSEQNUMBER_FIELD_NUMBER = 4;
    private int linkseqnumber_;
    /**
     * <code>required int32 linkseqnumber = 4;</code>
     */
    public boolean hasLinkseqnumber() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 linkseqnumber = 4;</code>
     */
    public int getLinkseqnumber() {
      return linkseqnumber_;
    }

    public static final int PREVHASH_FIELD_NUMBER = 5;
    private volatile java.lang.Object prevhash_;
    /**
     * <code>required string prevhash = 5;</code>
     */
    public boolean hasPrevhash() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string prevhash = 5;</code>
     */
    public java.lang.String getPrevhash() {
      java.lang.Object ref = prevhash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prevhash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prevhash = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrevhashBytes() {
      java.lang.Object ref = prevhash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prevhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private volatile java.lang.Object signature_;
    /**
     * <code>required string signature = 6;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string signature = 6;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signature = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 7;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string message = 7;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPublickey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLinkpublickey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLinkseqnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrevhash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publickey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, seqnumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, linkpublickey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, linkseqnumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, prevhash_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signature_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publickey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, seqnumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, linkpublickey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, linkseqnumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, prevhash_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signature_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block)) {
        return super.equals(obj);
      }
      nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block other = (nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block) obj;

      boolean result = true;
      result = result && (hasPublickey() == other.hasPublickey());
      if (hasPublickey()) {
        result = result && getPublickey()
            .equals(other.getPublickey());
      }
      result = result && (hasSeqnumber() == other.hasSeqnumber());
      if (hasSeqnumber()) {
        result = result && (getSeqnumber()
            == other.getSeqnumber());
      }
      result = result && (hasLinkpublickey() == other.hasLinkpublickey());
      if (hasLinkpublickey()) {
        result = result && getLinkpublickey()
            .equals(other.getLinkpublickey());
      }
      result = result && (hasLinkseqnumber() == other.hasLinkseqnumber());
      if (hasLinkseqnumber()) {
        result = result && (getLinkseqnumber()
            == other.getLinkseqnumber());
      }
      result = result && (hasPrevhash() == other.hasPrevhash());
      if (hasPrevhash()) {
        result = result && getPrevhash()
            .equals(other.getPrevhash());
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPublickey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublickey().hashCode();
      }
      if (hasSeqnumber()) {
        hash = (37 * hash) + SEQNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getSeqnumber();
      }
      if (hasLinkpublickey()) {
        hash = (37 * hash) + LINKPUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getLinkpublickey().hashCode();
      }
      if (hasLinkseqnumber()) {
        hash = (37 * hash) + LINKSEQNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getLinkseqnumber();
      }
      if (hasPrevhash()) {
        hash = (37 * hash) + PREVHASH_FIELD_NUMBER;
        hash = (53 * hash) + getPrevhash().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Block)
        nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.internal_static_message_Block_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.internal_static_message_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.class, nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.Builder.class);
      }

      // Construct using nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publickey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        seqnumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        linkpublickey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        linkseqnumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        prevhash_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.internal_static_message_Block_descriptor;
      }

      public nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block getDefaultInstanceForType() {
        return nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.getDefaultInstance();
      }

      public nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block build() {
        nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block buildPartial() {
        nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block result = new nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publickey_ = publickey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seqnumber_ = seqnumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.linkpublickey_ = linkpublickey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.linkseqnumber_ = linkseqnumber_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.prevhash_ = prevhash_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block) {
          return mergeFrom((nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block other) {
        if (other == nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block.getDefaultInstance()) return this;
        if (other.hasPublickey()) {
          bitField0_ |= 0x00000001;
          publickey_ = other.publickey_;
          onChanged();
        }
        if (other.hasSeqnumber()) {
          setSeqnumber(other.getSeqnumber());
        }
        if (other.hasLinkpublickey()) {
          bitField0_ |= 0x00000004;
          linkpublickey_ = other.linkpublickey_;
          onChanged();
        }
        if (other.hasLinkseqnumber()) {
          setLinkseqnumber(other.getLinkseqnumber());
        }
        if (other.hasPrevhash()) {
          bitField0_ |= 0x00000010;
          prevhash_ = other.prevhash_;
          onChanged();
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000020;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000040;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPublickey()) {
          return false;
        }
        if (!hasSeqnumber()) {
          return false;
        }
        if (!hasLinkpublickey()) {
          return false;
        }
        if (!hasLinkseqnumber()) {
          return false;
        }
        if (!hasPrevhash()) {
          return false;
        }
        if (!hasSignature()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object publickey_ = "";
      /**
       * <code>required string publickey = 1;</code>
       */
      public boolean hasPublickey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string publickey = 1;</code>
       */
      public java.lang.String getPublickey() {
        java.lang.Object ref = publickey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            publickey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string publickey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPublickeyBytes() {
        java.lang.Object ref = publickey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publickey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string publickey = 1;</code>
       */
      public Builder setPublickey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publickey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string publickey = 1;</code>
       */
      public Builder clearPublickey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publickey_ = getDefaultInstance().getPublickey();
        onChanged();
        return this;
      }
      /**
       * <code>required string publickey = 1;</code>
       */
      public Builder setPublickeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publickey_ = value;
        onChanged();
        return this;
      }

      private int seqnumber_ ;
      /**
       * <code>required int32 seqnumber = 2;</code>
       */
      public boolean hasSeqnumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 seqnumber = 2;</code>
       */
      public int getSeqnumber() {
        return seqnumber_;
      }
      /**
       * <code>required int32 seqnumber = 2;</code>
       */
      public Builder setSeqnumber(int value) {
        bitField0_ |= 0x00000002;
        seqnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seqnumber = 2;</code>
       */
      public Builder clearSeqnumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seqnumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object linkpublickey_ = "";
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public boolean hasLinkpublickey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public java.lang.String getLinkpublickey() {
        java.lang.Object ref = linkpublickey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            linkpublickey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLinkpublickeyBytes() {
        java.lang.Object ref = linkpublickey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkpublickey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public Builder setLinkpublickey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        linkpublickey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public Builder clearLinkpublickey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        linkpublickey_ = getDefaultInstance().getLinkpublickey();
        onChanged();
        return this;
      }
      /**
       * <code>required string linkpublickey = 3;</code>
       */
      public Builder setLinkpublickeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        linkpublickey_ = value;
        onChanged();
        return this;
      }

      private int linkseqnumber_ ;
      /**
       * <code>required int32 linkseqnumber = 4;</code>
       */
      public boolean hasLinkseqnumber() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 linkseqnumber = 4;</code>
       */
      public int getLinkseqnumber() {
        return linkseqnumber_;
      }
      /**
       * <code>required int32 linkseqnumber = 4;</code>
       */
      public Builder setLinkseqnumber(int value) {
        bitField0_ |= 0x00000008;
        linkseqnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 linkseqnumber = 4;</code>
       */
      public Builder clearLinkseqnumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        linkseqnumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object prevhash_ = "";
      /**
       * <code>required string prevhash = 5;</code>
       */
      public boolean hasPrevhash() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string prevhash = 5;</code>
       */
      public java.lang.String getPrevhash() {
        java.lang.Object ref = prevhash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prevhash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string prevhash = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPrevhashBytes() {
        java.lang.Object ref = prevhash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prevhash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prevhash = 5;</code>
       */
      public Builder setPrevhash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        prevhash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prevhash = 5;</code>
       */
      public Builder clearPrevhash() {
        bitField0_ = (bitField0_ & ~0x00000010);
        prevhash_ = getDefaultInstance().getPrevhash();
        onChanged();
        return this;
      }
      /**
       * <code>required string prevhash = 5;</code>
       */
      public Builder setPrevhashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        prevhash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>required string signature = 6;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string signature = 6;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string signature = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signature = 6;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 6;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000020);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 6;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        signature_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 7;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string message = 7;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 7;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 7;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000040);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 7;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Block)
    }

    // @@protoc_insertion_point(class_scope:message.Block)
    private static final nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block();
    }

    public static nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    public nl.tudelft.cs4160.trustchain_android.message.TempBlockProto.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4nl/tudelft/cs4160/trustchain_android/T" +
      "empBlock.proto\022\007message\"\221\001\n\005Block\022\021\n\tpub" +
      "lickey\030\001 \002(\t\022\021\n\tseqnumber\030\002 \002(\005\022\025\n\rlinkp" +
      "ublickey\030\003 \002(\t\022\025\n\rlinkseqnumber\030\004 \002(\005\022\020\n" +
      "\010prevhash\030\005 \002(\t\022\021\n\tsignature\030\006 \002(\t\022\017\n\007me" +
      "ssage\030\007 \001(\tB>\n,nl.tudelft.cs4160.trustch" +
      "ain_android.messageB\016TempBlockProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Block_descriptor,
        new java.lang.String[] { "Publickey", "Seqnumber", "Linkpublickey", "Linkseqnumber", "Prevhash", "Signature", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
