// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nl/tudelft/cs4160/trustchain_android/TrustChainBlock.proto

package nl.tudelft.cs4160.trustchain_android.block;

public final class BlockProto {
  private BlockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrustChainBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.TrustChainBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes transaction = 1;</code>
     */
    com.google.protobuf.ByteString getTransaction();

    /**
     * <code>bytes public_key = 2;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>int32 sequence_number = 3;</code>
     */
    int getSequenceNumber();

    /**
     * <code>bytes link_public_key = 4;</code>
     */
    com.google.protobuf.ByteString getLinkPublicKey();

    /**
     * <code>int32 link_sequence_number = 5;</code>
     */
    int getLinkSequenceNumber();

    /**
     * <code>bytes previous_hash = 6;</code>
     */
    com.google.protobuf.ByteString getPreviousHash();

    /**
     * <code>bytes signature = 7;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    boolean hasInsertTime();
    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    com.google.protobuf.Timestamp getInsertTime();
    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder();
  }
  /**
   * Protobuf type {@code message.TrustChainBlock}
   */
  public  static final class TrustChainBlock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.TrustChainBlock)
      TrustChainBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrustChainBlock.newBuilder() to construct.
    private TrustChainBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrustChainBlock() {
      transaction_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      sequenceNumber_ = 0;
      linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      linkSequenceNumber_ = 0;
      previousHash_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrustChainBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              transaction_ = input.readBytes();
              break;
            }
            case 18: {

              publicKey_ = input.readBytes();
              break;
            }
            case 24: {

              sequenceNumber_ = input.readInt32();
              break;
            }
            case 34: {

              linkPublicKey_ = input.readBytes();
              break;
            }
            case 40: {

              linkSequenceNumber_ = input.readInt32();
              break;
            }
            case 50: {

              previousHash_ = input.readBytes();
              break;
            }
            case 58: {

              signature_ = input.readBytes();
              break;
            }
            case 66: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (insertTime_ != null) {
                subBuilder = insertTime_.toBuilder();
              }
              insertTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(insertTime_);
                insertTime_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tudelft.cs4160.trustchain_android.block.BlockProto.internal_static_message_TrustChainBlock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tudelft.cs4160.trustchain_android.block.BlockProto.internal_static_message_TrustChainBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.class, nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.Builder.class);
    }

    public static final int TRANSACTION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString transaction_;
    /**
     * <code>bytes transaction = 1;</code>
     */
    public com.google.protobuf.ByteString getTransaction() {
      return transaction_;
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 2;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 3;
    private int sequenceNumber_;
    /**
     * <code>int32 sequence_number = 3;</code>
     */
    public int getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int LINK_PUBLIC_KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString linkPublicKey_;
    /**
     * <code>bytes link_public_key = 4;</code>
     */
    public com.google.protobuf.ByteString getLinkPublicKey() {
      return linkPublicKey_;
    }

    public static final int LINK_SEQUENCE_NUMBER_FIELD_NUMBER = 5;
    private int linkSequenceNumber_;
    /**
     * <code>int32 link_sequence_number = 5;</code>
     */
    public int getLinkSequenceNumber() {
      return linkSequenceNumber_;
    }

    public static final int PREVIOUS_HASH_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString previousHash_;
    /**
     * <code>bytes previous_hash = 6;</code>
     */
    public com.google.protobuf.ByteString getPreviousHash() {
      return previousHash_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 7;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int INSERT_TIME_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp insertTime_;
    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    public boolean hasInsertTime() {
      return insertTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    public com.google.protobuf.Timestamp getInsertTime() {
      return insertTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp insert_time = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder() {
      return getInsertTime();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!transaction_.isEmpty()) {
        output.writeBytes(1, transaction_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(2, publicKey_);
      }
      if (sequenceNumber_ != 0) {
        output.writeInt32(3, sequenceNumber_);
      }
      if (!linkPublicKey_.isEmpty()) {
        output.writeBytes(4, linkPublicKey_);
      }
      if (linkSequenceNumber_ != 0) {
        output.writeInt32(5, linkSequenceNumber_);
      }
      if (!previousHash_.isEmpty()) {
        output.writeBytes(6, previousHash_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(7, signature_);
      }
      if (insertTime_ != null) {
        output.writeMessage(8, getInsertTime());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!transaction_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, transaction_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      if (sequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sequenceNumber_);
      }
      if (!linkPublicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, linkPublicKey_);
      }
      if (linkSequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, linkSequenceNumber_);
      }
      if (!previousHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, previousHash_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, signature_);
      }
      if (insertTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getInsertTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock)) {
        return super.equals(obj);
      }
      nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock other = (nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock) obj;

      boolean result = true;
      result = result && getTransaction()
          .equals(other.getTransaction());
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && (getSequenceNumber()
          == other.getSequenceNumber());
      result = result && getLinkPublicKey()
          .equals(other.getLinkPublicKey());
      result = result && (getLinkSequenceNumber()
          == other.getLinkSequenceNumber());
      result = result && getPreviousHash()
          .equals(other.getPreviousHash());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && (hasInsertTime() == other.hasInsertTime());
      if (hasInsertTime()) {
        result = result && getInsertTime()
            .equals(other.getInsertTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransaction().hashCode();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceNumber();
      hash = (37 * hash) + LINK_PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getLinkPublicKey().hashCode();
      hash = (37 * hash) + LINK_SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getLinkSequenceNumber();
      hash = (37 * hash) + PREVIOUS_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousHash().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      if (hasInsertTime()) {
        hash = (37 * hash) + INSERT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getInsertTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.TrustChainBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.TrustChainBlock)
        nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.tudelft.cs4160.trustchain_android.block.BlockProto.internal_static_message_TrustChainBlock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.tudelft.cs4160.trustchain_android.block.BlockProto.internal_static_message_TrustChainBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.class, nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.Builder.class);
      }

      // Construct using nl.tudelft.cs4160.trustchain_android.message.BlockProto.TrustChainBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        transaction_ = com.google.protobuf.ByteString.EMPTY;

        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        sequenceNumber_ = 0;

        linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;

        linkSequenceNumber_ = 0;

        previousHash_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        if (insertTimeBuilder_ == null) {
          insertTime_ = null;
        } else {
          insertTime_ = null;
          insertTimeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.tudelft.cs4160.trustchain_android.block.BlockProto.internal_static_message_TrustChainBlock_descriptor;
      }

      public nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock getDefaultInstanceForType() {
        return nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.getDefaultInstance();
      }

      public nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock build() {
        nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock buildPartial() {
        nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock result = new nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock(this);
        result.transaction_ = transaction_;
        result.publicKey_ = publicKey_;
        result.sequenceNumber_ = sequenceNumber_;
        result.linkPublicKey_ = linkPublicKey_;
        result.linkSequenceNumber_ = linkSequenceNumber_;
        result.previousHash_ = previousHash_;
        result.signature_ = signature_;
        if (insertTimeBuilder_ == null) {
          result.insertTime_ = insertTime_;
        } else {
          result.insertTime_ = insertTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock) {
          return mergeFrom((nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock other) {
        if (other == nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock.getDefaultInstance()) return this;
        if (other.getTransaction() != com.google.protobuf.ByteString.EMPTY) {
          setTransaction(other.getTransaction());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getSequenceNumber() != 0) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.getLinkPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setLinkPublicKey(other.getLinkPublicKey());
        }
        if (other.getLinkSequenceNumber() != 0) {
          setLinkSequenceNumber(other.getLinkSequenceNumber());
        }
        if (other.getPreviousHash() != com.google.protobuf.ByteString.EMPTY) {
          setPreviousHash(other.getPreviousHash());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.hasInsertTime()) {
          mergeInsertTime(other.getInsertTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString transaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes transaction = 1;</code>
       */
      public com.google.protobuf.ByteString getTransaction() {
        return transaction_;
      }
      /**
       * <code>bytes transaction = 1;</code>
       */
      public Builder setTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes transaction = 1;</code>
       */
      public Builder clearTransaction() {
        
        transaction_ = getDefaultInstance().getTransaction();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 2;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 2;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 2;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private int sequenceNumber_ ;
      /**
       * <code>int32 sequence_number = 3;</code>
       */
      public int getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>int32 sequence_number = 3;</code>
       */
      public Builder setSequenceNumber(int value) {
        
        sequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sequence_number = 3;</code>
       */
      public Builder clearSequenceNumber() {
        
        sequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString linkPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes link_public_key = 4;</code>
       */
      public com.google.protobuf.ByteString getLinkPublicKey() {
        return linkPublicKey_;
      }
      /**
       * <code>bytes link_public_key = 4;</code>
       */
      public Builder setLinkPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes link_public_key = 4;</code>
       */
      public Builder clearLinkPublicKey() {
        
        linkPublicKey_ = getDefaultInstance().getLinkPublicKey();
        onChanged();
        return this;
      }

      private int linkSequenceNumber_ ;
      /**
       * <code>int32 link_sequence_number = 5;</code>
       */
      public int getLinkSequenceNumber() {
        return linkSequenceNumber_;
      }
      /**
       * <code>int32 link_sequence_number = 5;</code>
       */
      public Builder setLinkSequenceNumber(int value) {
        
        linkSequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 link_sequence_number = 5;</code>
       */
      public Builder clearLinkSequenceNumber() {
        
        linkSequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString previousHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes previous_hash = 6;</code>
       */
      public com.google.protobuf.ByteString getPreviousHash() {
        return previousHash_;
      }
      /**
       * <code>bytes previous_hash = 6;</code>
       */
      public Builder setPreviousHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        previousHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes previous_hash = 6;</code>
       */
      public Builder clearPreviousHash() {
        
        previousHash_ = getDefaultInstance().getPreviousHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 7;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 7;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 7;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp insertTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> insertTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public boolean hasInsertTime() {
        return insertTimeBuilder_ != null || insertTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public com.google.protobuf.Timestamp getInsertTime() {
        if (insertTimeBuilder_ == null) {
          return insertTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
        } else {
          return insertTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public Builder setInsertTime(com.google.protobuf.Timestamp value) {
        if (insertTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          insertTime_ = value;
          onChanged();
        } else {
          insertTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public Builder setInsertTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (insertTimeBuilder_ == null) {
          insertTime_ = builderForValue.build();
          onChanged();
        } else {
          insertTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public Builder mergeInsertTime(com.google.protobuf.Timestamp value) {
        if (insertTimeBuilder_ == null) {
          if (insertTime_ != null) {
            insertTime_ =
              com.google.protobuf.Timestamp.newBuilder(insertTime_).mergeFrom(value).buildPartial();
          } else {
            insertTime_ = value;
          }
          onChanged();
        } else {
          insertTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public Builder clearInsertTime() {
        if (insertTimeBuilder_ == null) {
          insertTime_ = null;
          onChanged();
        } else {
          insertTime_ = null;
          insertTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getInsertTimeBuilder() {
        
        onChanged();
        return getInsertTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder() {
        if (insertTimeBuilder_ != null) {
          return insertTimeBuilder_.getMessageOrBuilder();
        } else {
          return insertTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getInsertTimeFieldBuilder() {
        if (insertTimeBuilder_ == null) {
          insertTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getInsertTime(),
                  getParentForChildren(),
                  isClean());
          insertTime_ = null;
        }
        return insertTimeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.TrustChainBlock)
    }

    // @@protoc_insertion_point(class_scope:message.TrustChainBlock)
    private static final nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock();
    }

    public static nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrustChainBlock>
        PARSER = new com.google.protobuf.AbstractParser<TrustChainBlock>() {
      public TrustChainBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TrustChainBlock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrustChainBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrustChainBlock> getParserForType() {
      return PARSER;
    }

    public nl.tudelft.cs4160.trustchain_android.block.BlockProto.TrustChainBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_TrustChainBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_TrustChainBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:nl/tudelft/cs4160/trustchain_android/T" +
      "rustChainBlock.proto\022\007message\032\037google/pr" +
      "otobuf/timestamp.proto\"\345\001\n\017TrustChainBlo" +
      "ck\022\023\n\013transaction\030\001 \001(\014\022\022\n\npublic_key\030\002 " +
      "\001(\014\022\027\n\017sequence_number\030\003 \001(\005\022\027\n\017link_pub" +
      "lic_key\030\004 \001(\014\022\034\n\024link_sequence_number\030\005 " +
      "\001(\005\022\025\n\rprevious_hash\030\006 \001(\014\022\021\n\tsignature\030" +
      "\007 \001(\014\022/\n\013insert_time\030\010 \001(\0132\032.google.prot" +
      "obuf.TimestampBD\n,nl.tudelft.cs4160.trus" +
      "tchain_android.messageB\024TrustChainBlockP",
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_message_TrustChainBlock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_TrustChainBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_TrustChainBlock_descriptor,
        new java.lang.String[] { "Transaction", "PublicKey", "SequenceNumber", "LinkPublicKey", "LinkSequenceNumber", "PreviousHash", "Signature", "InsertTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
